// The README prose for each direction. Voice differs per direction — the
// markdown is part of the design, not a wrapper around it.
// Constraints applied throughout: ASHFORDE(TM) never (R) [EUIPO pending];
// YANA reachable only via yanaops.com, never a repo link; collaborative tone
// toward ESA and primes; no AI-vendor attribution; every figure traceable.

export const readmes = {
E: `<!-- Generated by tools/render.mjs. Every figure is measured, never typed. -->
%%HERO%%

## Start here

If you are evaluating us, these three tell you the most, fastest:

- **[yanaops.com](https://yanaops.com)** — the open mission-operations standard. **Pre-release**: read it, implement it, hold us to it.
- **[kshana.dev](https://kshana.dev)** — a validated PNT simulator you can run yourself and check our arithmetic.
- **[ashforde.org](https://ashforde.org)** — the company in one page: premise, domains, approach, standing.

**[→ Explore the figures interactively](https://ashforde.org/githubprofile/)** — hover any day, filter by language, sort the projects. The cards below are static images; that page is not.

%%DOMAINS%%

## Open engineering

Most of what we build is confidential. These are the pieces we publish, because a
standard nobody can inspect is not a standard.

%%PROJECT-YANA%%

> **YANA·Ops is pre-release.** Nothing is published to npm, PyPI or crates, and no
> version is tagged. **7** operations are marketed and **17** are cross-validated against an
> independent implementation, on a path to 50 and then 150. When it ships it ships with the
> conformance suite, not before. Read the standard now at **[yanaops.com](https://yanaops.com)**.

%%PROJECT-KSHANA%%

%%PROJECT-GRASP%%

## Working languages

Measured across all **{{REPOS}}** repositories, private included. Private repositories are
counted, never named. Each badge links to that language's home.

%%LANGUAGE_BADGES%%

%%STACK%%

## Activity

%%ACTIVITY%%

%%STANDING%%

## Research

%%RESEARCH%%

Discovered by author query, so a new preprint appears here without anyone editing this file.

<details>
<summary>Read the preprints</summary>

- [**2607.06212**](https://arxiv.org/abs/2607.06212) — The Cost of Lunar South-Polar Geometry, and Surface Beacons as the Efficient Fix — *astro-ph.EP*, 7 Jul 2026
- [**2607.02566**](https://arxiv.org/abs/2607.02566) — Earth-baseline VLBI restores the observability of a lunar surface station in joint orbit-and-clock determination — *eess.SP*, 29 Jun 2026
- [**2606.24210**](https://arxiv.org/abs/2606.24210) — A Conditional Timing Protection Level: Holdover-Limited Undetected Time Error Under GNSS Spoofing — *eess.SP*, 23 Jun 2026
- [**2607.05415**](https://arxiv.org/abs/2607.05415) — How Stable Is a PNT Resilience Score? Decision-Instability of Single-Number Composites — *cs.CR*, 22 Jun 2026
- [**2606.22054**](https://arxiv.org/abs/2606.22054) — Anticipating the Optimism Gap: Predicting Distribution-Shift Degradation of RF-Impairment Detectors — *eess.SP*, 20 Jun 2026

</details>

%%COMMITMENTS%%

## What we are doing now

- **Publishing the operations standard** — taking YANA·Ops from pre-release to a first tagged release, conformance suite included.
- **Extending validated coverage** — cross-validation from 17 operations toward 50, each differenced against an independent implementation.
- **Writing the methods down** — preprints first, so results can be reproduced and contested before they are relied on.
- **Talking to operators** — conversations with the people who fly spacecraft, and the institutions that must answer for the decisions.

## Conversations held in confidence

**[contact@ashforde.org](mailto:contact@ashforde.org)** · [ashforde.org](https://ashforde.org) · [LinkedIn](https://www.linkedin.com/company/ashfordeou/) · [arXiv](https://arxiv.org/a/baweja_c_1)

<details>
<summary>Company facts</summary>

| | |
|---|---|
| Legal entity | Ashforde OÜ |
| Registry code | 17321180, Estonian Commercial Register |
| Registered office | Ahtri tn 12, 15551 Tallinn, Estonia |
| Operating base | Frankfurt, Germany |
| Founder and director | Chakshu Baweja |
| Languages | English · Français · Deutsch · Italiano · Español · Eesti · Nederlands |
| Trademark | ASHFORDE™ — Ashforde OÜ |

</details>

<details>
<summary>How this page stays current</summary>

Every figure is measured, not typed. A scheduled workflow regenerates the whole page daily:

| Source | What it feeds |
|---|---|
| GitHub GraphQL | contribution calendar, public/private split, streak, peak day |
| GitHub REST | repository count, language mass across **all** repositories, releases |
| arXiv API | preprints, discovered by author query — new papers appear unprompted |

A GitHub README runs no JavaScript, so the cards above are images with links and tooltips.
The genuinely interactive version lives at
**[ashforde.org/githubprofile](https://ashforde.org/githubprofile/)**.

</details>`,
};
